export SPRING_DATASOURCE_URL="jdbc:postgresql://SERVER_NAME.postgres.database.azure.com:5432/DB_NAME"
export SPRING_DATASOURCE_USERNAME="whatever"
export SPRING_DATASOURCE_PASSWORD="yAYaasLNyWqyYIgJjLR4l6EmBJcyKQRzDIpOIGcvOaM="
export SPRING_DATASOURCE_SHOW_SQL="true"
