name: ci-cd-appservice

on:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - 'api/**'  
  workflow_dispatch:
    

jobs:
  build_deploy_infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set default Azure subscription
        run: az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Create Azure resource group
        run: |
              az deployment sub create \
               --location ${{ secrets.AZURE_LOCATION }} \
               --template-file ./deployment-rg.bicep \
               --parameters name=${{ secrets.AZURE_RESOURCE_GROUP }} location=${{ secrets.AZURE_LOCATION }}

      - name: Deploy Azure resources
        run: |
              adminName="a`openssl rand -hex 12`"
              adminPassword=`openssl rand -base64 22`
              dbUserName="u`openssl rand -hex 12`"
              dbUserPassword=`openssl rand -base64 22`
              #get public ip fromm outside
              clientIP=`dig +short myip.opendns.com @resolver1.opendns.com.`
              echo "My IP: $clientIP"

              dbConnectionString="host=${{ secrets.AZURE_DB_NAME }}.postgres.database.azure.com port=5432 dbname=${{ secrets.AZURE_DB_NAME }} user=$adminName password=$adminPassword sslmode=require"
               
              printf "$dbConnectionString" >tmp.txt
              cat ./tmp.txt
               
              az deployment group create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file ./deployment.bicep \
                            --parameters location=${{ secrets.AZURE_LOCATION }}  \
                                         dbServerName=${{ secrets.AZURE_DB_SERVER_NAME }} \
                                         dbName=${{ secrets.AZURE_DB_NAME }} \
                                         dbAdminName=$adminName \
                                         dbAdminPassword=$adminPassword \
                                         dbUserName=$dbUserName \
                                         dbUserPassword=$dbUserPassword \
                                         apiServiceName=${{ secrets.AZURE_API_SERVICE_NAME }} \
                                         apiServicePort=${{ secrets.AZURE_API_SERVICE_PORT }} \
                                         webServiceName=${{ secrets.AZURE_WEB_SERVICE_NAME }} \
                                         webServicePort=${{ secrets.AZURE_WEB_SERVICE_PORT }} \
                                         clientIPAddress=$clientIP
               
               
               
               dbUserExists=`psql "${dbConnectionString}" -tAc "SELECT 1 FROM pg_roles WHERE rolname='$dbUserName'"`
               
               if [ $dbUserExists -ne '1' ]
               then
                 psql "${dbConnectionString}" -tAc "SELECT 1 FROM pg_roles WHERE rolname='$dbUserName'"
                 psql "${dbConnectionString}" -tAc "CREATE USER $dbUserName WITH PASSWORD '$dbUserPassword';"
                 psql "${dbConnectionString}" -tAc "GRANT CONNECT ON DATABASE $dbName TO $dbUserName;"
                 psql "${dbConnectionString}" -tAc "GRANT USAGE ON SCHEMA public TO $dbUserName;"
                 psql "${dbConnectionString}" -tAc "GRANT SELECT ON todo TO $dbUserName;"
               endif

               psql "${dbConnectionString}" --file=./scripts/db.sql
  build_api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    outputs:
      RELEASE_VERSION: ${{ steps.version.outputs.RELEASE_VERSION }}
      RELEASE_NAME: ${{ steps.version.outputs.RELEASE_NAME }}
      RELEASE_FILE_NAME: ${{ steps.version.outputs.RELEASE_FILE_NAME }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Build the .jar
        run: |
          ./mvnw clean package -DskipTests
      
      - name: Figure out the version info
        id: version
        run: |
          cd ./target
          files=(api*.jar)
          mv "$files" "./api-${GITHUB_SHA}.jar"
          ls -la
          cd ..
          echo "::set-output name=RELEASE_VERSION::${GITHUB_SHA}"
          echo "::set-output name=RELEASE_NAME::api-${GITHUB_SHA}"
          echo "::set-output name=RELEASE_FILE_NAME::api-${GITHUB_SHA}.jar"
          
      - name: Display next version
        run: |
          echo "Version: ${{ steps.version.outputs.RELEASE_VERSION }}"
          echo "Release name: ${{ steps.version.outputs.RELEASE_NAME }}"
          echo "Release file name: ${{ steps.version.outputs.RELEASE_FILE_NAME }}"
      
      - name: 'Upload build artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.version.outputs.RELEASE_NAME }}
          path: ./api/target/${{ steps.version.outputs.RELEASE_FILE_NAME }}
          retention-days: 5
  
  deploy_api:
    needs: [build_api, build_deploy_infra]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v3

  build_web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
  deploy_web:
    needs: [build_web, build_deploy_infra]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3
  
